name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libsqlite3-0 libvips curl

      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        run: bin/rails db:setup test

      - name: Run system tests
        run: PARALLEL_WORKERS=1 bin/rails test:system

  lint:
    name: Lint & Security
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Rubocop
        run: bin/rubocop --format github

      - name: Bundler audit
        run: bundle exec bundler-audit check --update

      - name: Brakeman
        run: bundle exec brakeman --quiet --no-pager --exit-on-warn --exit-on-error
